name: Publish to PyPI test

permissions:
  id-token: write

on:
  push:
    branches:
      - tests_and_publishing
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: Build and Publish
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-versions: [3.12.2]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build wheels and source tarball
        run: >-
          poetry build

      - name: show temporary files
        run: >-
          ls -l

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        #with:
        #  user: __token__
        #  password: ${{ secrets.PYPI_API_TOKEN }}
        #skip-existing: true
